### ISSUE TITLE
theme namespace

### ISSUE THREAD

**Issue by silymer** [ashmaroli/jekyll-data#35]
I have a theme with a little long name, like `jekyll-theme-xxxx-xxx`. The theme have some config variables, like
```yaml
theme: jekyll-theme-xxxx-xxx

xxxx:
  someKey: someValue
```

I use the variables as `site.xxxx.someKey` in my templates. However i find it a little boring to refer them. 

I noticed that you registered a default namespace for theme: [theme-name], which is awesome!!!  

However, if i want to refer to my variables as `theme.someKey`, i have to change the namespace `xxxx` to `jekyll-theme-xxxx-xx` which is the theme name. But i still want to refer some variables directly, I have to do it like `site.jekyll-theme-xxxx-xxx.anotherKey` instead of `site.xxxx.anotherKey`. 

What i mean, **is it possible to give me a chance to specify a short theme namespace key, as a primary choice?** Like: 
```yaml
theme: jekyll-theme-xxxx-xx

theme_namespace: xxxx

xxxx:
  someKey: someValue
  anotherKey: anotherValue
```
By this way, i can use `theme.someKey` or directly `site.xxxx.anotherKey` in templates then.

Thank you!
